Create grc path
pkic/pkic.org pull request #111
Opened 2024-02-09 18:29 UTC by grcpath

![GRC PATH Logo](https://github.com/pkic/pkic.org/assets/159156556/972c361e-44de-4894-8a05-95633d39c1d5)

2024-02-09 19:49 UTC, vanbroup commented
@grcpath thanks for this pull request, but please note that the pull request is empty.

The image in the comment above doesn’t seem to be an original vector but be traced from a jpg/png, can you provide an original vector such as .ai or .svg?

2024-02-09 19:50 UTC, vanbroup requested changes

2024-02-09 19:50 UTC, vanbroup commented on assets/images/members/grc path
> +
No image here, it’s empty

2024-02-10 10:08 UTC, grcpath commented
Dear PaulThanks alot for your replyI have attached the SVG file. I will try to add it again and pull request. Best, AliSent from my Galaxy
-------- Original message --------From: Paul van Brouwershaven ***@***.***> Date: 2/9/24  10:49 PM  (GMT+03:00) To: "pkic/pkic.org" ***@***.***> Cc: grcpath ***@***.***>, Mention ***@***.***> Subject: Re: [pkic/pkic.org] Create grc path (PR #111) 
@grcpath thanks for this pull request, but please note that the pull request is empty.
The image in the comment above doesn’t seem to be an original vector but be traced from a jpg/png, can you provide an original vector such as .ai or .svg?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-02-10 12:39 UTC, grcpath commented
![GRC Path Logo (1)](https://github.com/pkic/pkic.org/assets/159156556/d42003ea-306f-49ae-a9e9-fc12d35f07ca)

2024-02-10 12:40 UTC, grcpath commented
Hi 
I had upload ne svg file

2024-02-10 14:28 UTC, vanbroup commented on assets/images/members/grc-path/grc-path.svg
> +  <image id="Vector_Smart_Object.svg" data-name="Vector Smart Object.svg" x="1402" y="812" width="2195" height="2195" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAACJMAAAiTCAYAAAADyYQ3AAAgA
This is not a vector image but a vector with an embedded png.

 `xlink:href="data:img/png;base64,`

2024-03-08 07:26 UTC, vanbroup commented on assets/images/members/grc-path/grc-path.svg
> +  <image id="Vector_Smart_Object.svg" data-name="Vector Smart Object.svg" x="1402" y="812" width="2195" height="2195" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAACJMAAAiTCAYAAAADyYQ3AAAgA
@grcpath any updates on this?

2024-05-30 11:32 UTC, svenska-primekey commented on assets/images/members/grc-path/grc-path.svg
> +  <image id="Vector_Smart_Object.svg" data-name="Vector Smart Object.svg" x="1402" y="812" width="2195" height="2195" xlink:href="data:img/png;base64,iVBORw0KGgoAAAANSUhEUgAACJMAAAiTCAYAAAADyYQ3AAAgA
@grcpath Have you had a chance to get an SVN logo without the embedded png?

2024-06-22 14:23 UTC, svenska-primekey commented
Closing, no update from GRC Path to provide a SVG logo.

2024-06-22 14:23 UTC, closed without merging