CALM member addition
pkic/pkic.org pull request #28
Opened 2022-09-22 17:44 UTC by tomgron

2022-09-23 11:37 UTC, tomgron commented
@vanbroup could you review this please?

2022-09-23 13:56 UTC, vanbroup commented
Thanks for the PR, I will review hopefully next week, else the week after.

2022-10-10 08:27 UTC, vanbroup requested changes

2022-10-13 22:23 UTC, tomgron commented on data/members/calm.yaml
> +name: CALM Oy
Change applied

2022-10-13 22:23 UTC, tomgron commented on data/members/calm.yaml
> +memberType: Vendor
Change applied

2022-10-13 22:27 UTC, tomgron commented on data/members/calm.yaml
> +   - name: Tommi Grönlund
Added picture

2022-10-13 22:27 UTC, tomgron commented on data/members/calm.yaml
> +     description: Managing director of CALM Oy
Added longer description

2022-10-13 22:28 UTC, tomgron commented on content/members/calm.md
> +CALM Oy is the provider of https://clm.fi which is a Certificate Lifecycle Management as a Service.
Added a bit longer description. At the moment we are still in process of developing our offering further so I'd like to update this periodically as our offering extends (at the moment working on ACME renewals)

2022-10-21 14:29 UTC, merged