add member info for ISC, correct typos in Entrust and KeyFactor .md files
pkic/pkic.org pull request #33
Opened 2023-03-15 05:28 UTC by markowitz-isc

2023-04-04 09:49 UTC, vanbroup requested changes

2023-04-04 09:52 UTC, vanbroup commented
Thanks for the pull request, I have split the PR into one to fix the spelling error you found and one to add Information Security Corp. as a member.

Please update the logo as this is currently containing some additional whitespace and actual text instead of rasterized text that shows the same irrespective of the device that is loading the logo.

2023-05-10 14:01 UTC, vanbroup commented
Looking forward to the update

2023-05-31 07:07 UTC, vanbroup commented on assets/images/members/infoseccorp/infoseccorp.svg
Any updates on this?

2023-08-28 12:43 UTC, vanbroup commented
@markowitz-isc looking forward to your updates so that we can close this PR

2023-09-06 15:56 UTC, markowitz-isc commented
@vanbroup Sorry, Paul. Working on this now...

2023-09-07 11:04 UTC, vanbroup commented
> @vanbroup Hopefully one of these will work for your needs. Thanks!
> 
> ![ISClogo-Corp_white](https://user-images.githubusercontent.com/16615009/266069216-745ba666-4cd6-444d-ab5c-e413ff554dea.png) ![ISClogo-Corp_Black](https://user-images.githubusercontent.com/16615009/266069219-792d7c0e-b0ec-4aa7-b67e-dcffee342b93.png)

Unfortunately this is not a vector image like an SVG but a PNG (pixel) image.

2023-09-07 13:12 UTC, blackbird1999 commented
[logos.zip](https://github.com/pkic/pkic.org/files/12549436/logos.zip)
@vanbroup The original Adobe Illustrator (.ai) and its exported SVG are in the attached zip. Thank you.

2023-09-07 13:15 UTC, blackbird1999 commented
![ISClogo-Corp_Spread_Out_Black - Raster](https://github.com/pkic/pkic.org/assets/16615009/9bf38cf8-7c78-4216-9c92-fb41582c1131)
And a slightly different SVG where I've, again, told Illustrator to rasterize the text...

2023-09-07 13:21 UTC, blackbird1999 commented
![ISClogo-Corp_Spread_Out_white - Raster](https://github.com/pkic/pkic.org/assets/16615009/dd32a7f1-40fd-4f7c-9411-bc14717aa68b)
And the white one...

2023-09-07 13:23 UTC, blackbird1999 commented
![ISClogo-Corp_Spread_Out_white - Raster](https://github.com/pkic/pkic.org/assets/16615009/aaa6c81e-1747-4be1-80f3-5699012c2e07)
And the continuing fight with Illustrator.

2023-09-07 13:26 UTC, vanbroup commented
I have updated the logo based on the AI file, hope that this one looks like the original:

https://github.com/pkic/pkic.org/blob/1ae9cff9b8b69a894dfb97cd66038108f6b9150c/assets/images/members/infoseccorp/infoseccorp.svg

2023-09-07 13:27 UTC, vanbroup approved these changes

2023-09-07 13:28 UTC, vanbroup commented
Merging for preview in isc branch

2023-09-07 13:28 UTC, merged