Update data digisign
pkic/pkic.org pull request #48
Opened 2023-06-22 06:19 UTC by budi-rahman

update data digisign

2023-08-28 12:41 UTC, vanbroup requested changes

2023-08-28 12:41 UTC, vanbroup commented on data/members/digisign-id.yaml
> +memberType: CA
The application of digisign.id is done under category F not A, can you please provide a link to your repository, audits and in which root stores you have been included?

2023-08-28 12:41 UTC, vanbroup commented on data/members/digisign-id.yaml
> +      linkedin: https://www.linkedin.com/in/pungkiarianto/
Please add a new line at the end

2023-08-28 12:41 UTC, vanbroup commented on assets/images/members/digisign-id/digisign-id.svg
This looks like a traced PNG file with a bad result, please provide a high quality vector, for example by saving a .ai file to .svg.

2024-02-06 09:33 UTC, vanbroup commented
@budi-rahman any updates on the pending comments?

2024-06-22 14:18 UTC, svenska-primekey commented
No update in 5 months. Changes made in MR #151

2024-06-22 14:18 UTC, closed without merging